name: PR continuous testing

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
    secrets: inherit

  docker:
    uses: ./.github/workflows/docker.yml
    needs: [test]
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    secrets: inherit
    with:
      tag: ${{ github.event.number }}
      push: false
