name: Create release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PRERELEASE: ${{ contains(inputs.tag, '-rc.') }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: motiva*
          merge-multiple: true

      - name: Attest
        uses: actions/attest@v4
        with:
          subject-path: ${{ github.workspace }}/motiva*

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          name: motiva ${{ inputs.tag }}
          generate_release_notes: true
          make_latest: ${{ env.PRERELEASE == 'false' }}
          draft: ${{ env.PRERELEASE == 'true' }}
          prerelease: ${{ env.PRERELEASE == 'true' }}
          files: motiva*

      - name: Publish prerelease
        uses: softprops/action-gh-release@v3
        if: ${{ env.PRERELEASE == 'true' }}
        with:
          name: motiva ${{ inputs.tag }}
          draft: false
