name: Create release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: motiva
      - uses: softprops/action-gh-release@v3
        with:
          name: motiva ${{ inputs.tag }}
          make_latest: ${{ !contains(inputs.tag, '-rc.') }}
          generate_release_notes: true
          prerelease: ${{ contains(inputs.tag, '-rc.') }}
          files: ${{ case(contains(inputs.tag, '-rc.'), 'motiva', '') }}
